# Shell variables
# Generated by 'wal'
wallpaper='/home/xubundadu/.customise/Wallpapers/Simple/sunset.png'

# Special
background='#0A1932'
foreground='#f6c8ab'
cursor='#f6c8ab'

# Colors
color0='#0A1932'
color1='#BA5C3E'
color2='#FD6A28'
color3='#A24D64'
color4='#E05755'
color5='#FF833C'
color6='#FF9251'
color7='#f6c8ab'
color8='#ac8c77'
color9='#BA5C3E'
color10='#FD6A28'
color11='#A24D64'
color12='#E05755'
color13='#FF833C'
color14='#FF9251'
color15='#f6c8ab'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
