#!/usr/bin/env bash
kitty +kitten icat --clear --stdin no --silent --transfer-mode file < /dev/null > /dev/tty

# Get the file type
MIME=$(file --mime-type -b "$1")
file=$1
w=$2
h=$3
x=$4
y=$5

# Rescale the image
w=$(( w * 99 / 100 ))
h=$(( h * 99 / 100 ))
y=$(( y + 1 ))

# Preview based on MIME type
case "$MIME" in
    # Text files
    text/*)
        bat --color=always --style=changes,numbers --terminal-width=$(tput cols) "$1"
        ;;
    # Markdown files
    application/x-markdown)
        bat --color=always --style=changes,numbers "$1"
        ;;
    # PDFs (using pdftotext)
    application/pdf)
        pdftotext "$1" - | bat --color=always --style=changes,numbers --terminal-width=$(tput cols) -
        ;;
    # Images (using chafa for terminal previews)
    image/*)
		# set polite on
		# chafa "$1"
		# chafa -f kitty --animate off --polite on "$1"
		# kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$1" < /dev/null > /dev/tty
        kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" < /dev/null > /dev/tty
        ;;
    # Default case for unknown types
    *)
        echo "Cannot preview this file type."
        ;;
esac
return 127
