# Shell variables
# Generated by 'wal'
wallpaper='/home/xubundadu/Downloads/johannes-plenio-hvrpOmuMrAI-unsplash.jpg'

# Special
background='#090C14'
foreground='#e5cca7'
cursor='#e5cca7'

# Colors
color0='#090C14'
color1='#675649'
color2='#926137'
color3='#AE6134'
color4='#97714A'
color5='#B28956'
color6='#D7A362'
color7='#e5cca7'
color8='#a08e74'
color9='#675649'
color10='#926137'
color11='#AE6134'
color12='#97714A'
color13='#B28956'
color14='#D7A362'
color15='#e5cca7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
