# Shell variables
# Generated by 'wal'
wallpaper='/home/xubundadu/.customise/Wallpapers/Simple/terminal_wallpaper.jpg'

# Special
background='#0B1830'
foreground='#f5c8c6'
cursor='#f5c8c6'

# Colors
color0='#0B1830'
color1='#F8657D'
color2='#7A4F82'
color3='#A45181'
color4='#E25783'
color5='#FB7585'
color6='#FC9194'
color7='#f5c8c6'
color8='#ab8c8a'
color9='#F8657D'
color10='#7A4F82'
color11='#A45181'
color12='#E25783'
color13='#FB7585'
color14='#FC9194'
color15='#f5c8c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
