#!/usr/bin/env bash

# @requires: pactl

status () {
  status=$(amixer get Capture | grep ": Capture.*\[" | sed "s/.*\[//" | uniq | sed "s/\]//")
  if [[ $status == 'on' ]]; then
    echo yes
  else
    echo no
  fi
}

set_volume () {
  local max_db=65536
  local percent=$1

  # getting the $percent% of $max_db
  local value=$(jq -n ${percent}/100*${max_db} | sed 's/\./ /g' | awk '{print $1}')

  # set volume
  pacmd set-source-volume $SINK $value
}

get () {
  local enabled=$(status)
  if [[ $enabled == 'no' ]]; then
    echo '0'
  else
    amixer get Capture | grep ": Capture.*\[" | sed "s/.*\[\([0-9]\+\)%\].*/\1/p" | uniq | sed "s/\]//"
  fi
}

percentage () {
  local val=$(get)
  echo "${val}%"
}

_ () {
  ${@}
  exit 0
}

if [[ $1 == "status" ]]; then
  _ status
fi

if [[ $1 == "toggle" ]]; then
  _ pactl set-source-mute $SINK toggle
  notify-send "Mic Toggle" "Mic Status: $(status)"
fi

if [[ $1 == "set" ]]; then
  _ set_volume ${2}
  notify-send "Mic Toggle" "Mic Status: $(status)"
fi

if [[ $1 == "get" ]]; then
  _ get
fi

if [[ $1 == "percent" ]]; then
  _ percentage
fi
